# Generated by Django 2.2.4 on 2020-09-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200906_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='feedback',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
