# Generated by Django 2.2.4 on 2020-09-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='about',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='feedback',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='None', max_length=22),
        ),
    ]
